#!/usr/bin/env bun

let input = '';

process.stdin.setEncoding('utf8');

// Read all from STDIN
process.stdin.on('readable', () => {
  const chunk = process.stdin.read();
  if (chunk !== null) {
    input += chunk;
  }
});

process.stdin.on('end', () => {
  // Reverse and write to STDOUT
  const reversed = input.split('').reverse().join('');
  process.stdout.write(reversed);
});
