.TH BLANKNOTE 1 blanknote\-VERSION
.SH NAME
BlankNote \- a damn simple note taking app 
.SH SYNOPSIS
.B blanknote
.RB [file]
.SH DESCRIPTION
BlankNote is written in C with GTK4. It has no UI elements except the text view, controlled with keybindings.
.SH USAGE
Run with blanknote [file]

.SH KEYBINDINGS
.TP
.B Ctrl\-plus
 Zoom text in
.TP
.B Ctrl\-minus
 Zoom text out
.TP
.B Ctrl\-0 
 Reset zooming level to default
.TP
.B Ctrl\-O
 Open file picker
.TP
.B Ctrl\-S
 Save file

